server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/api/users/**
        - id: listing-service
          uri: lb://listingservice
          predicates:
            - Path=/api/listings/**
        - id: booking-service
          uri: lb://bookingservice
          predicates:
            - Path=/api/bookings/**
        - id: payment-service
          uri: lb://paymentservice
          predicates:
            - Path=/api/payments/**
        - id: review-service
          uri: lb://reviewservice
          predicates:
            - Path=/api/reviews/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

